### ISSUE TITLE
Find speakers and  keynote speakers

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#5] opened 2020-03-05 22:35 UTC

**Comment by sayanchowdhury** [comment] 2020-03-05 22:39
cc: @anistark @ananyo2012 @chocos10

**Comment by iambibhas** [comment] 2020-03-08 05:46
Given the current scare that is going on, that's restricting people from traveling, it's going to be difficult to approach any international speaker about traveling in next 2-3 months, even if the event is in October, because nearly no one knows when this will get over. I'm hoping that things will get better by October, but we really dont know. Keeping that in mind, maybe think about having sessions by international speakers remotely? Have it as a backup plan at least.

**Comment by ananyo2012** [comment] 2020-03-08 15:18
Do we want to include the alternative in the very first email, or suggest
it in their reply ?

**Comment by iambibhas** [comment] 2020-03-08 17:36
I'd say it's an option only if they don't want to travel. So depends on their preference. Let's gather suggestions, approach them, and then see how it goes. I just wanted to mention it as an idea. Discuss it in the mailing list as well maybe.

**Comment by chocos10** [comment] 2020-03-09 11:20
Even I think we should keep remote sessions in mails from starting and approach speakers with this alternative.

**Comment by ananyo2012** [comment] 2020-03-09 12:04
I think it will be good to mention this in follow up email, since it will
be hard to finalize on their availability if we give this alternative from
starting.

**Comment by satyaakam** [comment] 2020-06-09 12:04
Duplicate of #46 and #47  we can close this one

**Closed as completed** 2020-06-13 06:40 UTC
Labels: wg/cfp
